### ISSUE TITLE
Some Question in FuseMoE

### ISSUE THREAD

**Issue by anothersin** [carlwharris/cog-bias-med-LLMs#3]
HI,

I'm very sorry for asking FuseMoE related questions in this repository, as there is no place to submit issues in [FuseMoE.](https://github.com/aaronhan223/Multimodal-Transformer/tree/83fca4042698308cd9af590676516ed8154c72b1)

When [preprocessing](https://github.com/aaronhan223/Multimodal-Transformer/tree/83fca4042698308cd9af590676516ed8154c72b1/mimiciv_preprocessing) the mimic-iv, we didn't find the generation code for ts_labs_vitals_icu.pkl, but there is a code for output [ts_labs_vitals.pkl,](https://github.com/aaronhan223/Multimodal-Transformer/blob/main/mimiciv_preprocessing/ts_irregular.ipynb) are they the same?

If not same could you please provide the generation code. And It would be great if the [google drive](https://github.com/aaronhan223/Multimodal-Transformer/blob/main/mimiciv_notes.md) mentioned here could be provided!

Also, when we tried to [embedd the ecg,](https://github.com/aaronhan223/Multimodal-Transformer/blob/83fca4042698308cd9af590676516ed8154c72b1/mimiciv_preprocessing/ecg_embeddings.ipynb) _'attia_encoder_256.keras'_ was not found. We observe that you mentioned in [your paper:](https://arxiv.org/pdf/2402.03226.pdf) _' We  adopt a convolutional autoencoder approach, adapted from Attia et al. (2019), that compresses each ECG into a 256-dimensional
vector.'_ Would it be possible to provide the training code, and it would be nice if it was already trained attia_encoder_256.keras.

**Comment by carlwharris** [comment]
No worries. We've added an issues page and I wrote a response [here](https://github.com/aaronhan223/Multimodal-Transformer/issues/1).

**Comment by carlwharris** [comment]
(Marking as complete, feel free to respond on the Multimodal-Transformer repo)
